spring:
  application:
    name: fu
  datasource:
    url: jdbc:mysql://localhost:3306/xiaofu?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml 